baseURL = "https://simpleguy.tech/"
languageCode = "en-us"
title = "Dig deeper-Try harder-Repeat"
staticDir = "static"
buildDraft = true
pygmentsOptions = "nowrap=True"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "monokai"

[params]
    disqusShortname = "asimpleguy"
    description = "I'm a simple guy."
    author = "simpleguy"

[taxonomies]
    category = "categories"
    tag = "tags"
    project = "projects"
